---  # display_user.yml

- hosts: localhost
  gather_facts: false

  vars_prompt:

    - name: user
      prompt: Utilisateur
      default: microlinux
      private: false

    - name: password
      prompt: Mot de passe
      default: yatahongaga
      private: true

  tasks:
    - debug:
        msg: "user is {{user}}, mdp is {{password}}"

...