---  # apache-suse.yml

- hosts: suse

  tasks:

    - name: Installation d'Apache
      zypper:
        name: apache2

    - name: Démarrage d'Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Personnalisation de la page
      copy:
        dest: /srv/www/htdocs/index.html
        mode: 0644
        content: |
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Serveur Apache Suse</title>
            </head>
            <body>
              <h1>Apache web server running on SUSE Linux.</h1>
            </body>
          </html>